---

#Registers New leaf
- name: Register new leafs
  hosts: apic
  connection: local
  gather_facts: false
  vars_files:
   - vars/register_leaf_vars.yml


#Creates even odd leaf, geo location, oob, leaf profile, leaf interface profile and vpc protection group
  tasks:
    - name: Registers odd leaf
      aci_fabric_node:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        serial: "{{ item['odd_sn'] }}"
        node_id: "{{ item['odd_id'] }}"
        switch: "{{ item['odd_name'] }}"
        role: leaf
        state: present
        validate_certs: False
      when: item['odd_id'] is not undefined
      with_items: "{{ pair }}"

    - name: Registers even leaf
      aci_fabric_node:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        serial: "{{ item['even_sn'] }}"
        node_id: "{{ item['even_id'] }}"
        switch: "{{ item['even_name'] }}"
        role: leaf
        state: present
        validate_certs: False
      when: item['even_id'] is not undefined
      with_items: "{{ pair }}"



    - name: Create Rack for odd node
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        path: /api/node/mo/uni/fabric/site-default/building-default/floor-default/room-default/rack-{{ item['odd_rack'] }}.json
        method: post
        content:
          {
            "geoRack": {
              "attributes": {
                "dn": "uni/fabric/site-default/building-default/floor-default/room-default/rack-{{ item['odd_rack'] }}",
                "name": "{{ item['odd_rack'] }}",
                "rn": "rack-{{ item['odd_rack'] }}",
                "status": "created"
              },
              "children": []
            }
          }
        validate_certs: False
      when: item['odd_id'] is not undefined
      with_items: "{{ pair }}"

    - name: Create Rack for even node
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        path: /api/node/mo/uni/fabric/site-default/building-default/floor-default/room-default/rack-{{ item['even_rack'] }}.json
        method: post
        content:
          {
            "geoRack": {
              "attributes": {
                "dn": "uni/fabric/site-default/building-default/floor-default/room-default/rack-{{ item['even_rack'] }}",
                "name": "{{ item['even_rack'] }}",
                "rn": "rack-{{ item['even_rack'] }}",
                "status": "created"
              },
              "children": []
            }
          }
        validate_certs: False
      when: item['even_id'] is not undefined
      with_items: "{{ pair }}"



    - name: add Rack for odd node
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        path: /api/node/mo/uni/fabric/site-default/building-default/floor-default/room-default/rack-{{ item['odd_rack'] }}.json
        method: post
        content:
          {
            "geoRsNodeLocation": {
              "attributes": {
                "tDn": "topology/pod-1/node-{{ item['odd_id'] }}",
                "status": "created,modified"
              },
              "children": []
            }
          }
        validate_certs: False
      when: item['odd_id'] is not undefined
      with_items: "{{ pair }}"

    - name: add Rack for even node
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        path: /api/node/mo/uni/fabric/site-default/building-default/floor-default/room-default/rack-{{ item['even_rack'] }}.json
        method: post
        content:
          {
            "geoRsNodeLocation": {
              "attributes": {
                "tDn": "topology/pod-1/node-{{ item['even_id'] }}",
                "status": "created,modified"
              },
              "children": []
            }
          }
        validate_certs: False
      when: item['even_id'] is not undefined
      with_items: "{{ pair }}"



    - name: Add ipv4 address to out of band mgmt interface for odd node
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        path: /api/node/mo/uni/tn-mgmt/mgmtp-default/oob-default/rsooBStNode-[topology/pod-1/node-{{ item['odd_id'] }}].json
        method: post
        content:
          {
            "mgmtRsOoBStNode": {
              "attributes": {
                "tDn": "topology/pod-1/node-{{ item['odd_id'] }}",
                "addr": "{{ item['odd_ip'] }}",
                "gw": "{{ item['ip_gw'] }}",
                "status": "created"
              },
              "children": []
            }
          }
        validate_certs: False
      when: item['odd_id'] is not undefined
      with_items: "{{ pair }}"

    - name: Add ipv4 address to out of band mgmt interface for even node
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        path: /api/node/mo/uni/tn-mgmt/mgmtp-default/oob-default/rsooBStNode-[topology/pod-1/node-{{ item['even_id'] }}].json
        method: post
        content:
          {
            "mgmtRsOoBStNode": {
              "attributes": {
                "tDn": "topology/pod-1/node-{{ item['even_id'] }}",
                "addr": "{{ item['even_ip'] }}",
                "gw": "{{ item['ip_gw'] }}",
                "status": "created"
              },
              "children": []
            }
          }
        validate_certs: False
      when: item['even_id'] is not undefined
      with_items: "{{ pair }}"

  

    - name: Add leaf profile for odd node
      aci_switch_policy_leaf_profile:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: Leaf_{{ item['odd_id'] }}
        state: present
        validate_certs: False
      when:
        - item['odd_id'] is not undefined
        - item['type'] == "standalone"
      with_items: "{{ pair }}"

    - name: Add leaf selector to leaf profile for odd node
      aci_switch_leaf_selector:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: Leaf_{{ item['odd_id'] }}
        leaf: "{{ item['odd_name'] }}"
        leaf_node_blk: "{{ item['odd_name'] }}"
        from: "{{ item['odd_id'] }}"
        to: "{{ item['odd_id'] }}"
        state: present
        validate_certs: False
      when:
        - item['odd_id'] is not undefined
        - item['type'] == "standalone"
      with_items: "{{ pair }}"



    - name: Add leaf profile for even node
      aci_switch_policy_leaf_profile:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: Leaf_{{ item['even_id'] }}
        state: present
        validate_certs: False
      when:
        - item['even_id'] is not undefined
        - item['type'] == "standalone"
      with_items: "{{ pair }}"

    - name: Add leaf selector to leaf profile for even node
      aci_switch_leaf_selector:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: Leaf_{{ item['even_id'] }}
        leaf: "{{ item['even_name'] }}"
        leaf_node_blk: "{{ item['even_name'] }}"
        from: "{{ item['even_id'] }}"
        to: "{{ item['even_id'] }}"
        state: present
        validate_certs: False
      when:
        - item['even_id'] is not undefined
        - item['type'] == "standalone"
      with_items: "{{ pair }}"



    - name: Add leaf profile for vpc nodes
      aci_switch_policy_leaf_profile:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: Leaf_{{ item['odd_id'] }}_{{ item['even_id'] }}
        state: present
        validate_certs: False
      when: 
        - item['odd_id'] is not undefined 
        - item['even_id'] is not undefined 
        - item['type'] == "VPC"
      with_items: "{{ pair }}"

    - name: Add leaf selector to leaf profile for odd node vpc
      aci_switch_leaf_selector:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: Leaf_{{ item['odd_id'] }}_{{ item['even_id'] }}
        leaf: "{{ item['odd_name'] }}"
        leaf_node_blk: "{{ item['odd_name'] }}"
        from: "{{ item['odd_id'] }}"
        to: "{{ item['odd_id'] }}"
        state: present
        validate_certs: False
      when:
        - item['odd_id'] is not undefined 
        - item['even_id'] is not undefined 
        - item['type'] == "VPC"
      with_items: "{{ pair }}"

    - name: Add leaf selector to leaf profile for even node vpc
      aci_switch_leaf_selector:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: Leaf_{{ item['odd_id'] }}_{{ item['even_id'] }}
        leaf: "{{ item['even_name'] }}"
        leaf_node_blk: "{{ item['even_name'] }}"
        from: "{{ item['even_id'] }}"
        to: "{{ item['even_id'] }}"
        state: present
        validate_certs: False
      when:
        - item['odd_id'] is not undefined 
        - item['even_id'] is not undefined 
        - item['type'] == "VPC"
      with_items: "{{ pair }}"




    - name: Add odd leaf interface profile
      aci_interface_policy_leaf_profile:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: LEAF{{ item['odd_id'] }}_IntfProfile
        state: present
        validate_certs: False
      when:
        - item['odd_id'] is not undefined 
        - item['type'] == "standalone"
      with_items: "{{ pair }}"

    - name: Add odd leaf interface profile to leaf profile
      aci_interface_selector_to_switch_policy_leaf_profile:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: Leaf_{{ item['odd_id'] }}
        interface_selector: LEAF{{ item['odd_id'] }}_IntfProfile
        state: present
        validate_certs: False
      when:
        - item['odd_id'] is not undefined 
        - item['type'] == "standalone"
      with_items: "{{ pair }}"



    - name: Add even leaf interface profile
      aci_interface_policy_leaf_profile:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: LEAF{{ item['even_id'] }}_IntfProfile
        state: present
        validate_certs: False
      when:
        - item['even_id'] is not undefined 
        - item['type'] == "standalone"
      with_items: "{{ pair }}"

    - name: Add even leaf interface profile to leaf profile
      aci_interface_selector_to_switch_policy_leaf_profile:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: Leaf_{{ item['even_id'] }}
        interface_selector: LEAF{{ item['even_id'] }}_IntfProfile
        state: present
        validate_certs: False
      when:
        - item['even_id'] is not undefined 
        - item['type'] == "standalone"
      with_items: "{{ pair }}"



    - name: Add vpc leaf interface profile
      aci_interface_policy_leaf_profile:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: LEAF{{ item['odd_id'] }}_LEAF{{ item['even_id'] }}_IntfProfile
        state: present
        validate_certs: False
      when:
        - item['odd_id'] is not undefined 
        - item['even_id'] is not undefined 
        - item['type'] == "VPC"
      with_items: "{{ pair }}"

    - name: Add vpc leaf interface profile to leaf profile
      aci_interface_selector_to_switch_policy_leaf_profile:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: Leaf_{{ item['odd_id'] }}_{{ item['even_id'] }}
        interface_selector: LEAF{{ item['odd_id'] }}_LEAF{{ item['even_id'] }}_IntfProfile
        state: present
        validate_certs: False
      when:
        - item['odd_id'] is not undefined 
        - item['even_id'] is not undefined 
        - item['type'] == "VPC"
      with_items: "{{ pair }}"



    - name: Add vpc leafs to protection group
      aci_switch_policy_vpc_protection_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        protection_group: VPC_Group_{{ item['odd_id'] }}_{{ item['even_id'] }}
        protection_group_id: "{{ item['odd_id'] }}"
        switch_1_id: "{{ item['odd_id'] }}"
        switch_2_id: "{{ item['even_id'] }}"
        vpc_domain_policy: default
        state: present
        validate_certs: False
      when:
        - item['odd_id'] is not undefined 
        - item['even_id'] is not undefined 
        - item['type'] == "VPC"
      with_items: "{{ pair }}"